# Setup
title: ZENG Tian
description: Welcome! This is a peaceful little world, drifting outside the great universe
url: https://TianZengSky.github.io
avatar: /Bai Zhi_2.jpg
paginate: 5
permalink: pretty
cover_image: /BG.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: vszhub
  card: summary
logo: logo.png
social:
  name: ZENG Tian
  links:
    - https://twitter.com/vszhub
    - https://github.com/TianZengSky
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Songzi Vong
  url: https://github.com/vshub/
  email: tianzeng7-c@my.cityu.edu.hk

# 启用代码一键复制
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    # 启用行号与复制按钮
    line_numbers: true
    start_line: 1
